version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: policyedgeai-api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - policyedgeai-network

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: policyedgeai-dashboard
    restart: always
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - policyedgeai-network

networks:
  policyedgeai-network:
    driver: bridge
