# Live Intelligence Feed Configuration

# Data Sources Configuration
default_rss_feeds:
  - name: "Reuters Business"
    url: "https://feeds.reuters.com/reuters/businessNews"
    categories: ["market_shock", "policy_shift"]
    enabled: true
    polling_interval: 300

  - name: "SEC Press Releases"  
    url: "https://www.sec.gov/news/pressreleases.rss"
    categories: ["regulatory_change"]
    enabled: true
    polling_interval: 600

  - name: "TechCrunch AI"
    url: "https://techcrunch.com/category/artificial-intelligence/feed/"
    categories: ["ai_development"]
    enabled: true
    polling_interval: 900

  - name: "Financial Times Markets"
    url: "https://www.ft.com/rss/home/us"
    categories: ["market_shock", "political_event"]
    enabled: true
    polling_interval: 300

# Web Scraping Sources
web_sources:
  - name: "SEC EDGAR Recent Filings"
    url: "https://www.sec.gov/edgar/search/"
    categories: ["regulatory_change"]
    enabled: false  # Requires more sophisticated scraping
    headers:
      User-Agent: "Mozilla/5.0 (PolicyEdgeAI Intelligence Bot)"

# Google Drive Integration (requires API setup)
google_drive:
  enabled: false
  service_account_file: "config/gdrive-service-account.json"
  monitored_folders:
    - "Intelligence Sources"
    - "Regulatory Updates"

# AIPRM Integration (requires authentication)
aiprm:
  enabled: false
  api_token: "${AIPRM_API_TOKEN}"
  chat_history_endpoint: "https://aiprm.com/api/chat-history"

# Tripwire Rules Configuration
default_tripwires:
  - name: "Market Crash Alert"
    pattern: "crash|plunge|collapse|fall|drop"
    category: "market_shock"
    threshold: 7.0
    enabled: true

  - name: "AI Breakthrough"
    pattern: "breakthrough|advancement|revolutionary|artificial intelligence|GPT|LLM"
    category: "ai_development"
    threshold: 6.0
    enabled: true

  - name: "Regulatory Emergency"
    pattern: "emergency|urgent|immediate|regulation|compliance|SEC|FDA"
    category: "regulatory_change"
    threshold: 8.0
    enabled: true

  - name: "Volatility Spike"
    pattern: "volatility|spike|surge|fluctuation|VIX"
    category: "volatility_alert"
    threshold: 6.5
    enabled: true

# Feed Configuration
default_feeds:
  - name: "Executive Intelligence Brief"
    description: "High-impact intelligence for C-suite and senior leadership"
    categories: ["market_shock", "regulatory_change", "political_event"]
    is_premium: true
    max_items: 50

  - name: "AI Development Monitor"
    description: "Latest developments in artificial intelligence and machine learning"
    categories: ["ai_development"]
    is_premium: false
    max_items: 100

  - name: "Market Intelligence"
    description: "Real-time market movements, volatility alerts, and financial intelligence"
    categories: ["market_shock", "volatility_alert"]
    is_premium: true
    max_items: 75

  - name: "Regulatory Watch"
    description: "Regulatory changes, compliance updates, and policy shifts"
    categories: ["regulatory_change", "policy_shift"]
    is_premium: false
    max_items: 100

# Learning System Configuration
learning_system:
  learning_cycle_interval_hours: 6
  min_actions_for_learning: 5
  personalization_strength: 0.5
  confidence_threshold: 0.6
  
  # Scoring weights for intelligence items
  scoring_weights:
    impact_weight: 0.4
    urgency_weight: 0.3
    risk_weight: 0.2
    confidence_weight: 0.1

# Monetization Configuration
monetization:
  tiers:
    free:
      max_feeds: 2
      max_memos_per_day: 1
      api_access: false
      categories: ["ai_development", "regulatory_change"]
      
    basic:
      max_feeds: 5
      max_memos_per_day: 3
      api_access: true
      price_monthly: 29.99
      
    premium:
      max_feeds: 10
      max_memos_per_day: 10
      api_access: true
      price_monthly: 99.99
      
    enterprise:
      max_feeds: unlimited
      max_memos_per_day: unlimited
      api_access: true
      custom_pricing: true

# Professional Packaging Configuration
memo_generation:
  templates:
    daily:
      max_items: 10
      sections: ["executive_summary", "key_insights", "risk_assessment", "recommendations"]
      
    weekly:
      max_items: 25
      sections: ["executive_summary", "key_insights", "market_analysis", "regulatory_updates", "ai_intelligence", "recommendations"]
      
    alert:
      max_items: 5
      sections: ["executive_summary", "immediate_actions", "risk_assessment"]

  branding:
    header_title: "Live Intelligence Memo"
    footer_text: "Generated by PolicyEdgeAI Intelligence System"
    classification_levels: ["INTERNAL", "CONFIDENTIAL", "RESTRICTED"]
    
# System Monitoring
monitoring:
  collection_interval_minutes: 15
  health_check_interval_minutes: 5
  max_errors_per_hour: 10
  alert_email: "admin@policyedgeai.com"